{
  lib,
  stdenvNoCC,
  runtimeShell,
  makeWrapper,

  python3,
  python3Packages,

  coreutils,
  findutils,
  gnused,
  gawk,
  gnumake,

  enscript,
  ghostscript,
  tesseract,
  poppler-utils,
  qpdf,

  texlive,
  gtk3,

  withTex ? false,
  withGtk ? false,
}:

let
  opencv = python3Packages.opencv4.override {
    enableGtk3 = withGtk;
  };

  pythonEnv = python3.withPackages (ps: [
    ps.numpy
    ps.pandas
    ps.pillow
    ps.pytesseract
    ps.pygments
    opencv
  ]);

  runtimeTools =
    [
      coreutils
      findutils
      gnused
      gawk
      gnumake

      enscript
      ghostscript
      tesseract
      poppler-utils
      qpdf

      pythonEnv
    ]
    ++ lib.optionals withTex [
      texlive.combined.scheme-full
    ]
    ++ lib.optionals withGtk [
      gtk3
    ];

  runtimePath = lib.makeBinPath runtimeTools;

  mkPythonWrapper = script: name: ''
    makeWrapper ${pythonEnv}/bin/python $out/bin/${name} \
      --add-flags "$out/share/mcq-grader/scripts/${script}" \
      --prefix PYTHONPATH : "$out/share/mcq-grader/scripts" \
      --prefix PATH : "${runtimePath}"
  '';
in
stdenvNoCC.mkDerivation {
  pname = "mcq-grader";
  version = "unstable-2026-07-30";

  # This expression lives in the MCQ Grader repository, so package the current
  # working tree instead of fetching a separately pinned upstream revision.
  src = lib.cleanSource ./.;

  nativeBuildInputs = [
    makeWrapper
  ];

  dontConfigure = true;
  dontBuild = true;

  installPhase = ''
    runHook preInstall

    mkdir -p $out/share/mcq-grader
    mkdir -p $out/bin

    cp -R scripts $out/share/mcq-grader/
    cp Makefile README.md LICENSE $out/share/mcq-grader/

    if [ -d sample-data ]; then
      cp -R sample-data $out/share/mcq-grader/
    fi

    ${mkPythonWrapper "generate_zones.py" "mcq-generate-zones"}
    ${mkPythonWrapper "process_sheets.py" "mcq-process-sheets"}
    ${mkPythonWrapper "verify_zones.py" "mcq-verify-zones"}
    ${mkPythonWrapper "grade_exams.py" "mcq-grade-exams"}
    ${mkPythonWrapper "map_zones_manually.py" "mcq-map-zones-manually"}

    makeWrapper ${gnumake}/bin/make $out/bin/mcq-grader-make \
      --add-flags "-f" \
      --add-flags "$out/share/mcq-grader/Makefile" \
      --add-flags "PYTHON=${pythonEnv}/bin/python" \
      --prefix PYTHONPATH : "$out/share/mcq-grader/scripts" \
      --prefix PATH : "${runtimePath}"

    cat > $out/bin/mcq-grader-copy-example <<'EOF'
#!${runtimeShell}
set -euo pipefail

dest="''${1:-mcq-grader-example}"

if [ "$#" -gt 1 ]; then
  echo "usage: mcq-grader-copy-example [DESTINATION]" >&2
  exit 2
fi

if [ -e "$dest" ]; then
  echo "error: destination already exists: $dest" >&2
  exit 1
fi

mkdir -p "$dest"

if [ -d "@out@/share/mcq-grader/sample-data" ]; then
  cp -R "@out@/share/mcq-grader/sample-data" "$dest/sample-data"
else
  echo "error: this build does not include sample-data" >&2
  exit 1
fi

cat > "$dest/Makefile" <<'MAKEFILE'
# Generated by mcq-grader-copy-example.
#
# This forwarding Makefile keeps the scripts and runtime dependencies in the
# installed Nix package while leaving exam inputs and generated files here.
PYTHON := ${pythonEnv}/bin/python
export PATH := ${runtimePath}:$(PATH)

include @out@/share/mcq-grader/Makefile
MAKEFILE

chmod -R u+rwX "$dest"

cat >&2 <<MSG
Copied MCQ Grader example to: $dest

Try:
  cd "$dest"
  mcq-grader-make show-config
  mcq-grader-make verify
  mcq-grader-make grade
MSG
EOF

    substituteInPlace $out/bin/mcq-grader-copy-example \
      --replace-fail "@out@" "$out"

    chmod +x $out/bin/mcq-grader-copy-example
    wrapProgram $out/bin/mcq-grader-copy-example \
      --prefix PATH : "${lib.makeBinPath [ coreutils ]}"

    runHook postInstall
  '';

  meta = {
    description = "Automated grading suite for multiple-choice answer sheets";
    homepage = "https://github.com/romildo/mcq-grader";
    license = lib.licenses.mit;
    maintainers = with lib.maintainers; [ romildo ];
    platforms = lib.platforms.linux;
    mainProgram = "mcq-grader-make";
  };
}
